config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
 
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'

  delete '/logout',  to: 'sessions#destroy'
  get '/login', to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  

  get '/auth/:provider/callback', to: 'sessions#omniauth'
  

  get '/settings', to: 'users#edit'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer"> 
    <small>
        The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
        by <a href="https://www.michaelhartl.com/">Michael Hartl</a> 
    </small>
    <nav> 
        <ul>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact", contact_path %></li>
            <li><a href="https://news.railstutorial.org/">News</a></li>
        </ul> 
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse"> 
    <%= javascript_include_tag "header", "data-track-turbo": "true", defer: true %>
    <div class="container">
        <%= link_to "sample app", root_path, id: "logo" %> 
        <nav>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed bar-btn" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span> 
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button> 
            </div>
            <div class=".bar-content">
                <ul class="nav navbar-nav navbar-right collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <li><%= link_to "Home", root_path %></li> 
                    <li><%= link_to "Help", help_path %></li> 
                    <% if logged_in? %>
                        <li><%= link_to "Users", users_path %></li>
                        <li class="dropdown show">
                            <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> 
                                Account <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu menu">
                                <li><%= link_to "Profile", user_path(current_user) %></li> 
                                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                                <li class="divider"></li>
                                <li>
                                    <%= link_to "Log out", destroy_user_session_path, data:{ turbo_method: :delete}  %> 
                                </li>
                            </ul> 
                        </li>
                    <% else %>
                        <li><%= link_to "Log in", new_user_session_path %></li>
                    <% end %>
                </ul> 
            </div>
        </nav>
    </div> 
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
<%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>

<%= javascript_importmap_tags %>
<%= javascript_include_tag "turbo", type: "module" %>
<%= javascript_include_tag "application", "data-track-turbo": "true", defer: true %>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"> </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title)%></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim'%>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= render "layouts/header"%>
    <div class="container"> 
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer"%>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>